{
  "contest": 119,
  "handle": "throttle",
  "address": "0x210b0D0694ff95c99dD693DD89CDF2f88de6beC4",
  "risk": "3",
  "title": "Denial of Service, Users/Pool owners are not able to withdraw invested funds",
  "issueId": 212,
  "issueUrl": "https://github.com/code-423n4/2022-05-factorydao-findings/issues/212"
}